/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dulma
 */
public class cashier extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
Statement st=null;
    /**
     * Creates new form cashier
     */
    public cashier() {
        initComponents();
        DisplayItems();
    }
      private void DisplayItems(){
    try{
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","");
        st=con.createStatement();
        rs=st.executeQuery("select * from user");
      cashierTable.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException e){
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cashierTable = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        lblCat2 = new javax.swing.JLabel();
        lblCat = new javax.swing.JLabel();
        lblcat1 = new javax.swing.JLabel();
        lblcashier = new javax.swing.JLabel();
        lblLout = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Billslbl = new javax.swing.JLabel();
        reportlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 18, 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 220, 215));

        cashierTable.setBackground(new java.awt.Color(246, 215, 195));
        cashierTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cashierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cashierTable.setRowHeight(25);
        jScrollPane1.setViewportView(cashierTable);

        deletebtn.setBackground(new java.awt.Color(255, 204, 51));
        deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
        });

        Updatebtn.setBackground(new java.awt.Color(255, 204, 51));
        Updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Updatebtn.setText("Update");
        Updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatebtnMouseClicked(evt);
            }
        });
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 154, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(deletebtn)
                        .addGap(72, 72, 72)
                        .addComponent(Updatebtn)
                        .addGap(497, 497, 497))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Updatebtn)
                    .addComponent(deletebtn))
                .addGap(96, 96, 96))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 1250, 650));

        lblCat2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblCat2.setForeground(new java.awt.Color(243, 229, 229));
        lblCat2.setText("Products");
        lblCat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCat2MouseClicked(evt);
            }
        });
        jPanel1.add(lblCat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        lblCat.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblCat.setForeground(new java.awt.Color(243, 229, 229));
        lblCat.setText("Categories");
        lblCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCatMouseClicked(evt);
            }
        });
        jPanel1.add(lblCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        lblcat1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblcat1.setForeground(new java.awt.Color(243, 229, 229));
        lblcat1.setText("Billing");
        lblcat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcat1MouseClicked(evt);
            }
        });
        jPanel1.add(lblcat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 30));

        lblcashier.setBackground(new java.awt.Color(232, 201, 119));
        lblcashier.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblcashier.setForeground(new java.awt.Color(232, 201, 119));
        lblcashier.setText("Cashier");
        lblcashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcashierMouseClicked(evt);
            }
        });
        jPanel1.add(lblcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 30));

        lblLout.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblLout.setForeground(new java.awt.Color(243, 229, 229));
        lblLout.setText("Logout");
        lblLout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoutMouseClicked(evt);
            }
        });
        jPanel1.add(lblLout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 90, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/cafe 3.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/logout3.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 229, 229));
        jLabel1.setText("View User Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 330, -1));

        Billslbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Billslbl.setForeground(new java.awt.Color(243, 229, 229));
        Billslbl.setText("Bills");
        Billslbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillslblMouseClicked(evt);
            }
        });
        jPanel1.add(Billslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 30));

        reportlbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        reportlbl.setForeground(new java.awt.Color(243, 229, 229));
        reportlbl.setText("Sales Report");
        reportlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportlblMouseClicked(evt);
            }
        });
        jPanel1.add(reportlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:
                                                  
    int selectedRow = cashierTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to update.");
        return;
    }

    // Retrieve existing values from the selected row
    String id = cashierTable.getValueAt(selectedRow, 0).toString();
    String name = JOptionPane.showInputDialog(this, "Enter new name:", cashierTable.getValueAt(selectedRow, 1).toString());
    String email = JOptionPane.showInputDialog(this, "Enter new email:", cashierTable.getValueAt(selectedRow, 2).toString());
    String mobile = JOptionPane.showInputDialog(this, "Enter new mobile number:", cashierTable.getValueAt(selectedRow, 3).toString());
    String password = JOptionPane.showInputDialog(this, "Enter new password:", cashierTable.getValueAt(selectedRow, 4).toString());
    String role = JOptionPane.showInputDialog(this, "Enter new role:", cashierTable.getValueAt(selectedRow, 5).toString());

    // Check if user inputs are valid
    if (name != null && email != null && mobile != null && password != null && role != null) {
        try {
            // Establish database connection
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe", "root", "");
            
            // Update query with all required fields
            String query = "UPDATE user SET name=?, email=?, mobileNumber=?, password=?, role=? WHERE id=?";
            pst = con.prepareStatement(query);
            
            // Set the parameters for the prepared statement
            pst.setString(1, name);
            pst.setString(2, email);
            pst.setString(3, mobile);
            pst.setString(4, password);
            pst.setString(5, role);
            pst.setString(6, id);
            
            // Execute the update
            pst.executeUpdate();
            
            // Show confirmation message
            JOptionPane.showMessageDialog(this, "User updated successfully.");
            
            // Refresh the table to show updated data
            DisplayItems();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
    }


    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void lblCat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCat2MouseClicked
        // TODO add your handling code here:
          new Items().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_lblCat2MouseClicked

    private void lblCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCatMouseClicked
        new manageCategory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCatMouseClicked

    private void lblcat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcat1MouseClicked
        // TODO add your handling code here:

        new Billing().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblcat1MouseClicked

    private void lblcashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcashierMouseClicked
        // TODO add your handling code here:
        new cashier().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblcashierMouseClicked

    private void lblLoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoutMouseClicked

        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLoutMouseClicked

    private void UpdatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UpdatebtnMouseClicked

    private void BillslblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillslblMouseClicked
        // TODO add your handling code here:
        new receipt().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BillslblMouseClicked

    private void reportlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportlblMouseClicked
        // TODO add your handling code here:
        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportlblMouseClicked

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        // TODO add your handling code here:
        int selectedRow = cashierTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        String id = cashierTable.getValueAt(selectedRow, 0).toString();
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe", "root", "");
                String query = "DELETE FROM user WHERE id=?";
                pst = con.prepareStatement(query);
                pst.setString(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "User deleted successfully.");
                DisplayItems(); // Refresh the table
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_deletebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Billslbl;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JTable cashierTable;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblCat2;
    private javax.swing.JLabel lblLout;
    private javax.swing.JLabel lblcashier;
    private javax.swing.JLabel lblcat1;
    private javax.swing.JLabel reportlbl;
    // End of variables declaration//GEN-END:variables
}
