/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.CategoryDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Dulma
 */
public class manageCategory extends javax.swing.JFrame {

    /**
     * Creates new form manageCategory
     */
    Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
Statement st=null;

    private DefaultTableModel tableModel;
    public manageCategory() {
        initComponents();
    }

private void DisplayItems(){
    try{
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","");
        st=con.createStatement();
        rs=st.executeQuery("select*from category");
      catTable.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException e){
        
    }
}
private void Clear(){
   
    txtid.setText("");
     txtName.setText("");
     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        catTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblproducts = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        sellinglbl = new javax.swing.JLabel();
        catlbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblcashier = new javax.swing.JLabel();
        Billslbl = new javax.swing.JLabel();
        reportlbl1 = new javax.swing.JLabel();
        reportlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(57, 18, 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 229, 229));
        jLabel2.setText("Manage category");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 320, -1));

        jPanel2.setBackground(new java.awt.Color(246, 220, 215));
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 92, 18));
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 60, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 270, 40));

        btnSave.setBackground(new java.awt.Color(255, 204, 51));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnSave.setForeground(new java.awt.Color(48, 10, 10));
        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, 30));

        btndelete.setBackground(new java.awt.Color(255, 204, 51));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btndelete.setForeground(new java.awt.Color(48, 10, 10));
        btndelete.setText("Delete");
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 95, 30));

        catTable.setBackground(new java.awt.Color(246, 215, 195));
        catTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        catTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category"
            }
        ));
        catTable.setRowHeight(25);
        catTable.setSelectionBackground(new java.awt.Color(211, 153, 69));
        catTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 560, 180));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(132, 84, 4));
        jLabel3.setText("View Category");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 140, -1));

        btnclear.setBackground(new java.awt.Color(255, 204, 51));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnclear.setForeground(new java.awt.Color(48, 10, 10));
        btnclear.setText("Clear");
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearMouseClicked(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel2.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 95, 30));

        btnedit.setBackground(new java.awt.Color(255, 204, 51));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnedit.setForeground(new java.awt.Color(48, 10, 10));
        btnedit.setText("Edit");
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
        });
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel2.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 95, 30));

        txtid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 270, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(192, 92, 18));
        jLabel4.setText("Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(132, 84, 4));
        jLabel5.setText("Add new Category");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 1230, 650));

        lblproducts.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblproducts.setForeground(new java.awt.Color(243, 229, 229));
        lblproducts.setText("Products");
        lblproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblproductsMouseClicked(evt);
            }
        });
        jPanel1.add(lblproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, -1));

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(243, 229, 229));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 120, -1));

        sellinglbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        sellinglbl.setForeground(new java.awt.Color(243, 229, 229));
        sellinglbl.setText("Billing");
        sellinglbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellinglblMouseClicked(evt);
            }
        });
        jPanel1.add(sellinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, -1));

        catlbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        catlbl.setForeground(new java.awt.Color(255, 204, 102));
        catlbl.setText("Categories");
        catlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catlblMouseClicked(evt);
            }
        });
        jPanel1.add(catlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/logout3.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 30, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/cafe 3.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 80));

        lblcashier.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblcashier.setForeground(new java.awt.Color(243, 229, 229));
        lblcashier.setText("Cashier");
        lblcashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcashierMouseClicked(evt);
            }
        });
        jPanel1.add(lblcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 30));

        Billslbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Billslbl.setForeground(new java.awt.Color(243, 229, 229));
        Billslbl.setText("Bills");
        Billslbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillslblMouseClicked(evt);
            }
        });
        jPanel1.add(Billslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 30));

        reportlbl1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        reportlbl1.setForeground(new java.awt.Color(243, 229, 229));
        reportlbl1.setText("Sales Report");
        reportlbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportlbl1MouseClicked(evt);
            }
        });
        jPanel1.add(reportlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 140, -1));

        reportlbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        reportlbl.setForeground(new java.awt.Color(243, 229, 229));
        reportlbl.setText("Sales Report");
        reportlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportlblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reportlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reportlbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      Category category=new Category();
      category.setName(txtName.getText());
      CategoryDao.save(category);
      setVisible(false);
      new manageCategory().setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) catTable.getModel();
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while (itr.hasNext()) {
            Category categoryObj = itr.next();
            dtm.addRow(new Object[]{categoryObj.getId(), categoryObj.getName()});
        }
        
    }//GEN-LAST:event_formComponentShown

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentShown

    private void catTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catTableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)catTable.getModel();
        int MyIndex=catTable.getSelectedRow();
        key=Integer.parseInt(model.getValueAt(MyIndex,0).toString());
         txtid.setText(model.getValueAt(MyIndex,0).toString());
        txtName.setText(model.getValueAt(MyIndex,1).toString());
       
    }//GEN-LAST:event_catTableMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void lblproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblproductsMouseClicked
        new Items().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_lblproductsMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        new login().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked

    }//GEN-LAST:event_btneditMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new manageCategory().setVisible(true);
    }//GEN-LAST:event_btndeleteActionPerformed
int key=0;
    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        // TODO add your handling code here:
        if(key==0){
            JOptionPane.showMessageDialog(this,"Select the category");
        }else{
            try{
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","");
             String Query="Delete from category where id="+key;
             Statement Del=con.createStatement();
             Del.executeUpdate(Query);
             JOptionPane.showMessageDialog(this, "Category Deleted");
              DisplayItems();
              Clear();
             
                
            }catch(Exception e){
                
            }
        }
                                                 

    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseClicked
        // TODO add your handling code here:
         Clear();
             
    }//GEN-LAST:event_btnclearMouseClicked

    private void sellinglblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellinglblMouseClicked
        // TODO add your handling code here:
        new Billing().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_sellinglblMouseClicked

    private void catlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_catlblMouseClicked

    private void lblcashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcashierMouseClicked
        // TODO add your handling code here:
        new cashier().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblcashierMouseClicked

    private void BillslblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillslblMouseClicked
        // TODO add your handling code here:
        new receipt().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BillslblMouseClicked

    private void reportlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportlblMouseClicked
        // TODO add your handling code here:
        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportlblMouseClicked

    private void reportlbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportlbl1MouseClicked
        // TODO add your handling code here:
        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportlbl1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Billslbl;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JTable catTable;
    private javax.swing.JLabel catlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblcashier;
    private javax.swing.JLabel lblproducts;
    private javax.swing.JLabel reportlbl;
    private javax.swing.JLabel reportlbl1;
    private javax.swing.JLabel sellinglbl;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
