/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dulma
 */
public class report extends javax.swing.JFrame {
Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        DisplayMonthlyReport();
    }
    private void Clear(){
  report.setText("");
   
}
    
  private void DisplayMonthlyReport() {
    try { 
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe", "root", "");
        st = con.createStatement();

        // Query for monthly sales
        String query = "SELECT * FROM bills WHERE MONTH(BillDate) = MONTH(CURRENT_DATE()) AND YEAR(BillDate) = YEAR(CURRENT_DATE())";
        rs = st.executeQuery(query);

        StringBuilder reportBuilder = new StringBuilder();
        reportBuilder.append("*****************************\n");
        reportBuilder.append("*       Monthly Sales Report       *\n");
        reportBuilder.append("*****************************\n\n");

        double totalSales = 0;
        int totalTransactions = 0;

        while (rs.next()) {
            int billId = rs.getInt("BId");
            String seller = rs.getString("sname");
            String date = rs.getString("BillDate");
            double amount = rs.getDouble("BAmt");

            totalSales += amount;
            totalTransactions++;

            reportBuilder.append("Bill ID: ").append(billId).append("\n");
            reportBuilder.append("Seller: ").append(seller).append("\n");
            reportBuilder.append("Date: ").append(date).append("\n");
            reportBuilder.append("Total Amount: ").append(amount).append("\n");
            reportBuilder.append("------------------------------\n");
        }

        // Calculate average transaction value
        double averageTransactionValue = totalSales / totalTransactions;

        reportBuilder.append("Total Sales for the Month: ").append(totalSales).append("\n");
        reportBuilder.append("Total Transactions: ").append(totalTransactions).append("\n");
        reportBuilder.append("Average Transaction Value: ").append(averageTransactionValue).append("\n");
        reportBuilder.append("*****************************\n\n");

        // Product-wise sales analysis
        reportBuilder.append("Product-Wise Sales Analysis\n");
        reportBuilder.append("*****************************\n");

        String productQuery = "SELECT products FROM bills WHERE MONTH(BillDate) = MONTH(CURRENT_DATE()) AND YEAR(BillDate) = YEAR(CURRENT_DATE())";
        rs = st.executeQuery(productQuery);

        while (rs.next()) {
            String products = rs.getString("products");
            reportBuilder.append(products).append("\n");
        }

        reportBuilder.append("*****************************\n");

        report.setText(reportBuilder.toString());

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e);
    }
}

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        report = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lblproducts = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        sellinglbl = new javax.swing.JLabel();
        catlbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblcashier = new javax.swing.JLabel();
        Billslbl = new javax.swing.JLabel();
        reportlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 18, 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 229, 229));
        jLabel2.setText("Sales Report");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 320, -1));

        jPanel2.setBackground(new java.awt.Color(246, 220, 215));
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        report.setColumns(20);
        report.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        report.setRows(5);
        jScrollPane1.setViewportView(report);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 840, 490));

        print.setBackground(new java.awt.Color(236, 189, 99));
        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setText("print");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel2.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 80, -1));

        btnclear.setBackground(new java.awt.Color(236, 189, 99));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(40, 10, 10));
        btnclear.setText("Clear");
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearMouseClicked(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel2.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 1250, 630));

        lblproducts.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblproducts.setForeground(new java.awt.Color(243, 229, 229));
        lblproducts.setText("Products");
        lblproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblproductsMouseClicked(evt);
            }
        });
        jPanel1.add(lblproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, -1));

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(243, 229, 229));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 120, -1));

        sellinglbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        sellinglbl.setForeground(new java.awt.Color(243, 229, 229));
        sellinglbl.setText("Billing");
        sellinglbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellinglblMouseClicked(evt);
            }
        });
        jPanel1.add(sellinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, -1));

        catlbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        catlbl.setForeground(new java.awt.Color(243, 229, 229));
        catlbl.setText("Categories");
        catlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catlblMouseClicked(evt);
            }
        });
        jPanel1.add(catlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/logout3.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 30, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/cafe 3.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 80));

        lblcashier.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblcashier.setForeground(new java.awt.Color(243, 229, 229));
        lblcashier.setText("Cashier");
        lblcashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcashierMouseClicked(evt);
            }
        });
        jPanel1.add(lblcashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 30));

        Billslbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Billslbl.setForeground(new java.awt.Color(243, 229, 229));
        Billslbl.setText("Bills");
        Billslbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillslblMouseClicked(evt);
            }
        });
        jPanel1.add(Billslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 30));

        reportlbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        reportlbl.setForeground(new java.awt.Color(255, 204, 102));
        reportlbl.setText("Sales Report");
        reportlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportlblMouseClicked(evt);
            }
        });
        jPanel1.add(reportlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblproductsMouseClicked
        new Items().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblproductsMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void sellinglblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellinglblMouseClicked
        // TODO add your handling code here:
        new Billing().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sellinglblMouseClicked

    private void catlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_catlblMouseClicked

    private void lblcashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcashierMouseClicked
        // TODO add your handling code here:
        new cashier().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblcashierMouseClicked

    private void BillslblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillslblMouseClicked
        // TODO add your handling code here:
        new receipt().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BillslblMouseClicked

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentShown

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
         try {
            report.print();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_printMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        DisplayMonthlyReport();
    }//GEN-LAST:event_printActionPerformed

    private void btnclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseClicked
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnclearMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void reportlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportlblMouseClicked
        // TODO add your handling code here:
        new report().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportlblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Billslbl;
    private javax.swing.JButton btnclear;
    private javax.swing.JLabel catlbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblcashier;
    private javax.swing.JLabel lblproducts;
    private javax.swing.JButton print;
    private javax.swing.JTextArea report;
    private javax.swing.JLabel reportlbl;
    private javax.swing.JLabel sellinglbl;
    // End of variables declaration//GEN-END:variables
}
